RED=`tput setaf 1`
YELLOW=`tput setaf 3`
LIGHT_YELLOW="\[\033[0;93m\]"
GREEN=`tput setaf 2`
BLUE=`tput setaf 4`
CYAN=`tput setaf 6`
LIGHT_RED="\[\033[1;31m\]"
LIGHT_GREEN="\[\033[1;32m\]"
WHITE=`tput setaf 7`
RESET=`tput sgr0`
BOLD=`tput bold`
BLACK=`tput setaf 0`
MAGENTA=`tput setaf 5`
